# https://medium.com/@puuga/deploy-to-firebase-hosting-with-github-actions-f795785fde6b
name: deploy_to_firebase_hosting

on: [push]
jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@main
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
